# Generated by Django 5.0.9 on 2024-11-17 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuariosite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("cpf", models.CharField(max_length=11)),
                ("datadenascimento", models.DateField()),
                ("nota", models.FloatField()),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo_conta",
                    models.CharField(
                        choices=[("professor", "Professor"), ("aluno", "Aluno")],
                        default="aluno",
                        max_length=20,
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="webknowledge.usuariosite",
                    ),
                ),
                ("qtdaulasassistidas", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="webknowledge.usuariosite",
                    ),
                ),
                ("qtdaulasfeitas", models.IntegerField()),
                ("disciplina", models.CharField(max_length=40)),
                ("especialidade", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota", models.FloatField()),
                ("comentario", models.CharField(max_length=200)),
                (
                    "avaliada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webknowledge.usuariosite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataAula", models.DateField()),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webknowledge.professor",
                    ),
                ),
            ],
        ),
    ]
