# Generated by Django 5.0.9 on 2024-11-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webknowledge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuariosite",
            name="perfil_imagem",
            field=models.ImageField(blank=True, null=True, upload_to="perfil_images/"),
        ),
    ]
