# Generated by Django 5.0.9 on 2024-11-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webknowledge", "0002_usuariosite_perfil_imagem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avaliacao",
            name="avaliada",
        ),
        migrations.AddField(
            model_name="professor",
            name="descricao",
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="qtdaulasassistidas",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="professor",
            name="disciplina",
            field=models.CharField(
                blank=True, default="Indefinido", max_length=40, null=True
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="especialidade",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="professor",
            name="qtdaulasfeitas",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Aula",
        ),
        migrations.DeleteModel(
            name="Avaliacao",
        ),
    ]
